version: "3.8"

services:
    backend:
        image: express-server
        build: 
            context: server
        environment:
            - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
            - PORT=${PORT}
        ports: 
            - "3000:${PORT}"
    database:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - 27018:27017